---

- name: MEDIUM | AZLX-23-000110 | AUDIT | Amazon Linux 2023 must ensure cryptographic verification of vendor software packages.
  when: az2023stig_000110
  tags:
    - azlx-23-000110
    - CAT2
    - SV-273995r1119973_rule
    - V-273995
    - SRG-OS-000366-GPOS-00153
    - NIST800-53R4_NA
    - encrypt
    - ssh
  block:
    - name: MEDIUM | AZLX-23-000110 | AUDIT | Amazon Linux 2023 must ensure cryptographic verification of vendor software packages.
      ansible.builtin.shell: "rpm -qa | grep {{ os_gpg_key_pubkey_name }}"  # noqa: command-instead-of-module
      changed_when: false
      failed_when: false
      register: discovered_os_installed_pub_keys

    - name: MEDIUM | AZLX-23-000110 | AUDIT | Amazon Linux 2023 must ensure cryptographic verification of vendor software packages.
      when: discovered_os_installed_pub_keys.rc == 0
      ansible.builtin.shell: 'rpm -q --queryformat "%{PACKAGER} %{VERSION}\\n" {{ os_gpg_key_pubkey_name }} | grep "{{ os_gpg_key_pubkey_content }}"'  # noqa: command-instead-of-module
      changed_when: false
      failed_when: false
      register: discovered_os_gpg_key_check

    - name: MEDIUM | AZLX-23-000110 | AUDIT | Amazon Linux 2023 must ensure cryptographic verification of vendor software packages.
      when: discovered_os_installed_pub_keys.rc == 1 or
            discovered_os_gpg_key_check.rc == 1
      ansible.builtin.debug:
        msg: "Warning!! Installed GPG Keys do not meet expected values or expected keys are not installed"

    - name: MEDIUM | AZLX-23-000110 | AUDIT | Amazon Linux 2023 must ensure cryptographic verification of vendor software packages.
      when: discovered_os_installed_pub_keys.rc == 1 or
            discovered_os_gpg_key_check.rc == 1
      vars:
        warn_control_id: "MEDIUM | AZLX-23-000110"
      ansible.builtin.import_tasks: warning_facts.yml

- name: MEDIUM | AZLX-23-000135 | PATCH | Amazon Linux 2023 systemd-journald service must be enabled.
  when: az2023stig_000135
  tags:
    - azlx-23-000135
    - CAT2
    - SV-274000r1119991_rule
    - V-274000
    - SRG-OS-000366-GPOS-00153
    - NIST800-53R4_NA
    - dnf
  ansible.builtin.systemd:
    name: systemd-journald
    state: started
    enabled: true
